apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
  labels:
    type: local
spec:
  storageClassName: "gp2"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/logstash"
