apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logstash-pvc
spec:
  storageClassName: "gp2"
  volumeName: logstash-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
